version: '3'

networks:
  rabril-hnet:
    name: rabril-hnet
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - rabril-hnet

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - rabril-hnet
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - rabril-hnet
    env_file:
      - .env

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/rabril-h/data/mysql
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/rabril-h/data/wordpress
      o: bind
